### ISSUE TITLE
Error installing the package

### ISSUE THREAD

**Issue by daemonslayer** [classfellow/node-threadobject#1]
I am trying to install the package in my project.
The error I got on using the command `npm i node-threadobject --save-dev` is :
```
> node-threadobject@0.4.47 install /home/cortana/Desktop/app/node_modules/node-threadobject
> node-gyp rebuild

make: Entering directory '/home/cortana/Desktop/app/node_modules/node-threadobject/build'
  CXX(target) Release/obj.target/node-threadobject/src/rcib.o
In file included from ../src/rcib.cc:6:0:
../src/callbackinfo.h:20:40: error: ‘WeakCallbackData’ in namespace ‘v8’ does not name a template type
     static void WeakCallback(const v8::WeakCallbackData<v8::Object, CallbackInfo>&);
                                        ^
../src/callbackinfo.h:20:56: error: expected ‘,’ or ‘...’ before ‘<’ token
     static void WeakCallback(const v8::WeakCallbackData<v8::Object, CallbackInfo>&);
                                                        ^
../src/callbackinfo.h: In constructor ‘rcib::CallbackInfo::CallbackInfo(v8::Isolate*, v8::Handle<v8::Object>, rcib::FreeCallback, void*)’:
../src/callbackinfo.h:58:43: error: no matching function for call to ‘v8::Persistent<v8::Object>::SetWeak(rcib::CallbackInfo*, <unresolved overloaded function type>)’
     persistent_.SetWeak(this, WeakCallback);
                                           ^
In file included from /home/cortana/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/rcib_object.h:8,
                 from ../src/rcib.h:8,
                 from ../src/rcib.cc:5:
/home/cortana/.node-gyp/7.2.1/include/node/v8.h:545:18: note: candidate: template<class P> void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = P; T = v8::Object]
   V8_INLINE void SetWeak(P* parameter,
                  ^
/home/cortana/.node-gyp/7.2.1/include/node/v8.h:545:18: note:   template argument deduction/substitution failed:
In file included from ../src/rcib.cc:6:0:
../src/callbackinfo.h:58:43: note:   candidate expects 3 arguments, 2 provided
     persistent_.SetWeak(this, WeakCallback);
                                           ^
In file included from /home/cortana/.node-gyp/7.2.1/include/node/node.h:42:0,
                 from ../src/rcib_object.h:8,
                 from ../src/rcib.h:8,
                 from ../src/rcib.cc:5:
/home/cortana/.node-gyp/7.2.1/include/node/v8.h:556:18: note: candidate: void v8::PersistentBase<T>::SetWeak() [with T = v8::Object]
   V8_INLINE void SetWeak();
                  ^
/home/cortana/.node-gyp/7.2.1/include/node/v8.h:556:18: note:   candidate expects 0 arguments, 2 provided
In file included from ../src/rcib.cc:6:0:
../src/callbackinfo.h: At global scope:
../src/callbackinfo.h:67:15: error: ‘WeakCallbackData’ in namespace ‘v8’ does not name a template type
     const v8::WeakCallbackData<v8::Object, CallbackInfo>& data) {
               ^
../src/callbackinfo.h:67:31: error: expected ‘,’ or ‘...’ before ‘<’ token
     const v8::WeakCallbackData<v8::Object, CallbackInfo>& data) {
                               ^
../src/callbackinfo.h: In static member function ‘static void rcib::CallbackInfo::WeakCallback(int)’:
../src/callbackinfo.h:68:5: error: ‘data’ was not declared in this scope
     data.GetParameter()->WeakCallback(data.GetIsolate(), data.GetValue());
     ^
node-threadobject.target.mk:111: recipe for target 'Release/obj.target/node-threadobject/src/rcib.o' failed
make: *** [Release/obj.target/node-threadobject/src/rcib.o] Error 1
make: Leaving directory '/home/cortana/Desktop/app/node_modules/node-threadobject/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-53-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/cortana/Desktop/app/node_modules/node-threadobject
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN app@1.0.0 No description
npm WARN app@1.0.0 No repository field.
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "node-threadobject" "--save-dev"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-threadobject@0.4.47 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-threadobject@0.4.47 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-threadobject package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-threadobject
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-threadobject
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cortana/Desktop/app/npm-debug.log

```
System Details:
OS: Ubuntu 16.04
gcc: 5.4.0

**Comment by classfellow** [comment]
Hi, I think node-gyp should be installed first.
`npm install -g node-gyp`
make a link for node-gyp, so you can run node-gyp -v  in any folder.
```
$ node-gyp -v
v3.4.0
$ 
```
Then run  `npm install node-threadobject --save-dev`
These steps may be able to solve your problem.
If some error still occurs.Enter the project directory, run `node-gyp rebuild`.

**Comment by classfellow** [comment]
fixed. `npm i node-threadobject@0.5.4`
